// Creates relay.env: hashed login password, agent key and session secret.
// Non-interactive: RELAY_PASSWORD=... node src/setup.js [--force]
import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import readline from 'node:readline';
import { fileURLToPath } from 'node:url';
import { hashPassword } from './auth.js';

const target = join(dirname(fileURLToPath(import.meta.url)), '..', 'relay.env');

if (existsSync(target) && !process.argv.includes('--force')) {
  console.error(`${target} already exists. Re-run with --force to replace it (this logs out every browser and changes the agent key).`);
  process.exit(1);
}

function askHidden(question) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: true });
    rl._writeToOutput = (s) => rl.output.write(s.startsWith(question) ? question : '');
    rl.question(question, (answer) => {
      rl.close();
      process.stdout.write('\n');
      resolve(answer);
    });
  });
}

let password = process.env.RELAY_PASSWORD;
if (!password) {
  password = await askHidden('Mật khẩu đăng nhập web: ');
  if ((await askHidden('Nhập lại mật khẩu: ')) !== password) {
    console.error('Hai lần nhập không khớp.');
    process.exit(1);
  }
}
if (password.length < 10) {
  console.error('Mật khẩu cần ít nhất 10 ký tự (trang web mở ra Internet).');
  process.exit(1);
}

const agentKey = randomBytes(32).toString('base64url');
const lines = [
  '# Generated by src/setup.js',
  'PORT=8090',
  'HOST=127.0.0.1',
  'TRUST_PROXY=1',
  `PASSWORD_HASH=${await hashPassword(password)}`,
  `AGENT_KEY=${agentKey}`,
  `SESSION_SECRET=${randomBytes(32).toString('base64url')}`,
  '',
];
writeFileSync(target, lines.join('\n'), { mode: 0o600 });

console.log(`Đã ghi ${target}`);
console.log('\nĐưa khóa sau vào file agent.env trên PC chạy LDPlayer (giữ bí mật):');
console.log(`AGENT_KEY=${agentKey}`);
